apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: ror-library-deploy
    process: web
  name: web-library-web-with-annotattions
spec:
  selector:
    matchLabels:
      app-name: ror-library-web
      process: web
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "devweb-app"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "secret/data/devwebapp/config"
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "secret/data/devwebapp/config" -}}
          username={{ .Data.data.username }};password={{ .Data.data.password }}
          {{- end -}}      
      labels:
        app-name: ror-library-web
        process: web
    spec:
      serviceAccountName: internal-app
      containers:
      - env:
        - name: PORT
          value: "3000"
#        envFrom:
#        - configMapRef:
#            name: bands-api
        image: grenader/ror:library3
        imagePullPolicy: IfNotPresent
        name: library2-web
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
