apiVersion: v1
kind: Service
metadata:
  name: ror-library
  labels:
    process: service
    app-name: ror-library-service
spec:
  type: LoadBalancer
  selector:
    app-name: ror-library-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000