---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ror-library-web
    process: web
  name: ror-library-deployment
spec:
  selector:
    matchLabels:
      app: ror-library-web
      process: web
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "devweb-app"
        vault.hashicorp.com/agent-inject-secret-vault-env.sh: "secret/data/devwebapp/config"
        vault.hashicorp.com/agent-inject-template-vault-env.sh: |
          {{- with secret "secret/data/devwebapp/config" -}}
          VAULT_VAR1={{ .Data.data.username }}
          VAULT_VAR2={{ .Data.data.password }}
          {{- end -}}
      labels:
        app: ror-library-web
        process: web
    spec:
      serviceAccountName: internal-app
      containers:
        - env:
          - name: PORT
            value: "3000"
          image: grenader/ror:library7
          imagePullPolicy: IfNotPresent
          name: ror-web
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: ror-library
  labels:
    process: service
    app: ror-library-web
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: ror-library-web
  type: LoadBalancer